// Socket blocks of the ARES_Mauer floor guides - generated by tools/make_guides.py from config/station.toml
// [guides] (edit the config and regenerate rather than this file). Use orientation: bottom on the MDF strip,
// pegs down; PRINT upside down (top face on the bed, pegs up). Units mm.
$fn = 96;
H = 22.000;          // [wall] base_z - [plates] mdf_t
R_TOP = 18.800;      // pin cone at the stone's underside + clearance
R_BOT = 8.830;      // the same cone at the block bottom
PEG_D = 8.000;
PEG_LEN = 3.000;

module socket_block_full() {
    difference() {
        translate([-80.000, -55.000, 0]) cube([160.000, 110.000, H]);
        for (q = [[-50.250, -26.500], [-50.250, 26.500], [50.250, -26.500], [50.250, 26.500]]) translate([q[0], q[1], -0.01]) cylinder(h = H + 0.02, r1 = R_BOT, r2 = R_TOP);
    }
    for (q = [[-60.000, 0.000], [60.000, 0.000]]) translate([q[0], q[1], -PEG_LEN]) cylinder(h = PEG_LEN + 0.5, d = PEG_D);
}

module socket_block_half() {
    difference() {
        translate([-30.000, -55.000, 0]) cube([60.000, 110.000, H]);
        for (q = [[0.000, -26.500], [0.000, 26.500]]) translate([q[0], q[1], -0.01]) cylinder(h = H + 0.02, r1 = R_BOT, r2 = R_TOP);
    }
    for (q = [[-22.000, 0.000], [22.000, 0.000]]) translate([q[0], q[1], -PEG_LEN]) cylinder(h = PEG_LEN + 0.5, d = PEG_D);
}

socket_block_full();
translate([0, 140, 0]) socket_block_half();
